### ISSUE TITLE
Seems don't have acceleration on the inference step

### ISSUE THREAD

**Issue by audreyeternal** [Mxbonn/INQ-pytorch#16]
Hi, 
I implemented your INQ framework on the UNet but seems like the inference time didn't decreased. The weights are still in the type of float32 although the values are the power of 2. I wonder if the bit shift operation can only be done on some specific devices like FPGA and on CPU/GPU the model after quantization still do float multiplication operations? Thank you!

**Comment by Mxbonn** [comment]
This paper and thus the implementation focuses more on the algorithm than on the actual deployment to specific hardware. Thus all parameters are still 32-bit floats but the amount of unique values used is artificially limited to what an N-bit value could use.

See also this issue in the implementation of the authors of the paper: https://github.com/AojunZhou/Incremental-Network-Quantization/issues/36
